### ISSUE TITLE
Update repo with new primer versions

### ISSUE THREAD

**Issue by carter-dpc** [artic-network/primer-schemes#18]
Hi Artic Team,

Would it be possible to add details of the most recent SARS-CoV-2 primer versions (including V5.3.2) to this repo as our nanopore pipeline queries this for primer details prior to data analysis.

Cheers,

Dan

**Comment by BioWilko** [comment]
Currently in the process of adding these to the `schemes_manifest.json` which is the preferred method of finding schemes since git clone and path parsing is extremely fragile and not recommended. You are welcome to use the fieldbioinformatics scheme downloader [here](https://github.com/artic-network/fieldbioinformatics/blob/8eb6a0c619030b137f8c97545aa1b763b94446db/artic/minion.py#LL44C1-L44C1) which will query the scheme manifest and fetch the specified version.

If this is absolutely not doable I can manually add the scheme files to this repo although we are hoping to move away from this approach in the future.

**Comment by BioWilko** [comment]
Schemes have now been added with formatting changes to maintain fieldbioinformatics compatibility.
